LEFT_HAND:
- ACTION_NAME: Fist
  POSITION:
  - 67
  - 151
  - 0
  - 0
  - 0
  - 0
- ACTION_NAME: Open
  POSITION:
  - 255
  - 179
  - 255
  - 255
  - 255
  - 255
RIGHT_HAND:
- ACTION_NAME: Open
  POSITION:
  - 255
  - 70
  - 255
  - 255
  - 255
  - 255
